

/*ALTER TABLES INSERTING FK CONTRAINTS*/

/*ALTER CUSTOMER*/
ALTER TABLE Customer
ADD CONSTRAINT FK_CityID FOREIGN KEY (CityID)
REFERENCES City (CityID);

/*ALTER ITEMSALE*/
ALTER TABLE ItemSale
ADD CONSTRAINT FK_SaleID FOREIGN KEY (SaleID)
REFERENCES Sale (SaleID);

ALTER TABLE ItemSale
ADD CONSTRAINT FK_ItemID FOREIGN KEY (ItemID)
REFERENCES Merchandise (ItemID);

/*ALTER MERCHANDISEORDER*/
ALTER TABLE MerchandiseOrder
ADD CONSTRAINT FK_Merch_SupplierID FOREIGN KEY (SupplierID)
REFERENCES SUPPLIER (SupplierID);

ALTER TABLE MerchandiseOrder
ADD CONSTRAINT FK_EmployeeID FOREIGN KEY (EmployeeID)
REFERENCES EMPLOYEE (Employee_ID);

/*ALTER SALE*/
ALTER TABLE Sale
ADD CONSTRAINT FK_CustomerID FOREIGN KEY (CustomerID)
REFERENCES Customer (CustomerID);


ALTER TABLE Sale
ADD CONSTRAINT FK_EmployeeID FOREIGN KEY (Employee_ID)
REFERENCES EMPLOYEE (Employee_ID);


/*ALTER ANIMALORDER*/
ALTER TABLE AnimalOrder
ADD CONSTRAINT FK_Animal_EmployeeID FOREIGN KEY (Employee_ID)
REFERENCES EMPLOYEE (Employee_ID);

ALTER TABLE AnimalOrder
ADD CONSTRAINT FK_Supplier_Animal_EmployeeID FOREIGN KEY (SupplierID)
REFERENCES SUPPLIER (SupplierID);

/*ALTER ANIMALSALE*/
ALTER TABLE AnimalSale
ADD CONSTRAINT FK__AnimalSaleID FOREIGN KEY (SaleID)
REFERENCES Sale (SaleID);

ALTER TABLE AnimalSale
ADD CONSTRAINT FK__Animal_SaleID FOREIGN KEY (AnimalID)
REFERENCES Animal (AnimalID);

/*ALTER ANIMAL*/
ALTER TABLE Animal
ADD CONSTRAINT FK_Category_Breed FOREIGN KEY (Category,Breed)
REFERENCES Breed (Category,Breed);


